package com.finscope.common.exception;

/**
 * 业务异常码。
 *
 * <p>{@link ErrorCode} 承载通用的、跨场景复用的错误语义（如“请求参数不合法”），
 * 而本枚举承载具体业务场景下的可读报错信息（如“研究运行不能为空”）。
 * 抛出异常时应直接引用本枚举，避免在代码中手写报错字符串。</p>
 *
 * <p>每个业务码关联一个通用 {@link ErrorCode}，用于复用其对外错误码和 HTTP 状态，
 * 从而无需改动统一响应与异常处理链路。</p>
 */
public enum BizErrorCode {
    // 研究任务图
    RESEARCH_RUN_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究运行不能为空"),
    RESEARCH_RUN_AND_THESIS_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究运行和命题不能为空"),

    // URL 摄入
    URL_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "URL 不能为空"),
    URL_SCHEME_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "仅支持 HTTP 或 HTTPS URL"),
    URL_MALFORMED(ErrorCode.REQUEST_PARAMETER_INVALID, "URL 格式不正确：%s"),
    URL_CONTENT_DYNAMIC_SHELL(ErrorCode.REQUEST_PARAMETER_INVALID,
            "未能读取到可用正文：该页面更像是登录/JavaScript 渲染壳页，无法生成可靠情报卡片。URL: %s"),
    URL_CONTENT_LINK_ONLY(ErrorCode.REQUEST_PARAMETER_INVALID,
            "未能读取到可用正文：检测到正文仅包含 X Article 链接，缺少实际内容。URL: %s。该推文可能包含长文内容，建议稍后重试或直接访问原链接。"),
    URL_CONTENT_TOO_SHORT(ErrorCode.REQUEST_PARAMETER_INVALID,
            "未能读取到可用正文：页面正文过短，无法生成可靠情报卡片。URL: %s"),

    // 市场情报
    DRAGON_TIGER_DAYS_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "龙虎榜查询天数仅支持 30、60、120"),

    // 文章分类
    ARTICLE_CATEGORY_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的文章分类：%s"),

    // 量化策略
    STRATEGY_PROMPT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "策略描述不能为空"),

    // 研究雷达
    RADAR_EVENT_STATE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "雷达事件处理状态不合法"),
    RADAR_OBSERVATION_STATE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "观察项状态不合法"),
    RADAR_OBSERVATION_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "观察项不存在"),
    RADAR_EVENT_ID_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "雷达事件不能为空"),
    RADAR_OBSERVATION_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "观察项不能为空"),
    RADAR_OBSERVATION_TOO_LONG(ErrorCode.REQUEST_PARAMETER_INVALID, "观察项不能超过300字"),
    RADAR_OBSERVATION_SYSTEM_UNDELETABLE(ErrorCode.BUSINESS_CONFLICT, "系统观察项不能删除"),

    // 分页与查询参数
    PAGE_REQUEST_INVALID_LEARNING_TASK(ErrorCode.REQUEST_PARAMETER_INVALID, "分页参数不合法"),
    PAGE_REQUEST_INVALID_KNOWLEDGE(ErrorCode.REQUEST_PARAMETER_INVALID, "知识分页参数不合法"),
    PAGE_REQUEST_INVALID_KNOWLEDGE_ENTRY(ErrorCode.REQUEST_PARAMETER_INVALID, "知识条目分页参数不合法"),
    CONTEXT_LIMIT_INVALID_EVIDENCE(ErrorCode.REQUEST_PARAMETER_INVALID, "证据上下文数量限制不合法"),
    CONTEXT_LIMIT_INVALID_EVENT(ErrorCode.REQUEST_PARAMETER_INVALID, "事件上下文数量限制不合法"),
    PROJECTION_BATCH_SIZE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "投影恢复批量大小不合法"),

    // 资金流查询参数
    CAPITAL_FLOW_INSTRUMENT_IDS_NULL(ErrorCode.REQUEST_PARAMETER_INVALID, "标的 ID 列表不能包含空值"),
    CAPITAL_FLOW_RANGE_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "起始时间、结束时间和快照时点均为必填"),
    CAPITAL_FLOW_RANGE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "起始时间不能晚于结束时间"),

    // Agent 学习任务
    AGENT_SUGGESTION_KEYS_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "Agent 建议缺少 eventId 或 taskKey"),

    // 资源不存在
    RESEARCH_MISSION_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "研究任务图不存在：%s"),
    QUANT_DATA_SYNC_RUN_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "进行中的量化数据同步任务不存在：%s"),
    MARKET_DATA_REFRESH_RUN_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "市场数据刷新任务不存在：%s"),

    // 业务状态冲突
    QUANT_EXPERIMENT_STATE_CHANGED(ErrorCode.BUSINESS_CONFLICT, "实验状态已变化，拒绝写入不一致结果：%s"),

    // 模型输出解析
    MODEL_OUTPUT_EMPTY(ErrorCode.LLM_SERVICE_ERROR, "模型返回空内容"),
    MODEL_OUTPUT_TOO_LONG(ErrorCode.LLM_SERVICE_ERROR, "模型输出超过字符上限"),
    MODEL_OUTPUT_NO_JSON(ErrorCode.LLM_SERVICE_ERROR, "模型输出中没有 JSON 对象"),
    MODEL_OUTPUT_JSON_INCOMPLETE(ErrorCode.LLM_SERVICE_ERROR, "模型输出中的 JSON 对象不完整"),
    MODEL_OUTPUT_JSON_UNPARSEABLE(ErrorCode.LLM_SERVICE_ERROR, "模型输出中没有可解析的 JSON 对象"),

    // 研究 Agent 决策与状态
    RESEARCH_AGENT_STATE_INPUT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "状态、决策和 Observation 不能为空"),
    RESEARCH_AGENT_STATE_CONFLICT(ErrorCode.DATA_VERSION_CONFLICT, "研究 Agent 状态发生并发更新，请从最新检查点恢复"),
    RESEARCH_AGENT_REPLAN_CONFLICT(ErrorCode.DATA_VERSION_CONFLICT, "研究 Agent 重规划状态发生并发更新"),
    RESEARCH_AGENT_VERIFY_CONFLICT(ErrorCode.DATA_VERSION_CONFLICT, "研究 Agent 完成校验状态发生并发更新"),
    RESEARCH_AGENT_TERMINATE_CONFLICT(ErrorCode.DATA_VERSION_CONFLICT, "研究 Agent 终止状态发生并发更新"),
    RESEARCH_DECISION_TASK_KEY_INVALID(ErrorCode.LLM_SERVICE_ERROR, "missionTaskKey 不属于服务端候选任务"),
    RESEARCH_DECISION_CONTEXT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究任务选择上下文不能为空"),
    RESEARCH_TASK_NOT_EXECUTABLE(ErrorCode.BUSINESS_CONFLICT, "研究任务当前不可执行：%s"),

    // 研究 Agent 工具
    RESEARCH_TOOL_ONLY_TOOL_CALL(ErrorCode.BUSINESS_CONFLICT, "只有 TOOL_CALL 决策可以进入工具调度器"),
    RESEARCH_TOOL_NO_OBSERVATION(ErrorCode.LLM_SERVICE_ERROR, "研究工具没有返回 Observation：%s"),
    RESEARCH_TOOL_ARGS_NOT_JSON(ErrorCode.LLM_SERVICE_ERROR, "持久化工具参数不是合法 JSON"),
    RESEARCH_TOOL_CONTEXT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究运行和决策 ID 不能为空"),
    RESEARCH_TOOL_ASSESS_NO_ARGS(ErrorCode.LLM_SERVICE_ERROR, "证据缺口评估不接受参数"),
    RESEARCH_TOOL_MATERIAL_ARGS_INVALID(ErrorCode.LLM_SERVICE_ERROR, "结构化资料检索参数必须且只能包含 stockCode、materialType 和 query"),
    RESEARCH_TOOL_MATERIAL_CODE_INVALID(ErrorCode.LLM_SERVICE_ERROR, "结构化资料检索仅支持六位 A 股代码"),
    RESEARCH_TOOL_MATERIAL_QUERY_INVALID(ErrorCode.LLM_SERVICE_ERROR, "结构化资料检索 query 未通过安全校验"),
    RESEARCH_TOOL_MATERIAL_TYPE_INVALID(ErrorCode.LLM_SERVICE_ERROR, "结构化资料检索 materialType 未通过安全校验"),
    RESEARCH_TOOL_NEWS_ARGS_INVALID(ErrorCode.LLM_SERVICE_ERROR, "公开资料搜索参数必须且只能包含 query 和 intent"),
    RESEARCH_TOOL_NEWS_QUERY_INVALID(ErrorCode.LLM_SERVICE_ERROR, "公开资料搜索 query 未通过安全校验"),
    RESEARCH_TOOL_NEWS_INTENT_INVALID(ErrorCode.LLM_SERVICE_ERROR, "公开资料搜索 intent 未通过安全校验"),
    SEARCH_PROVIDERS_ALL_UNAVAILABLE(ErrorCode.EXTERNAL_SERVICE_UNAVAILABLE, "所有搜索供应商均不可用"),

    // 研究规划与任务图
    RESEARCH_PLAN_ENRICH_NOT_OBJECT(ErrorCode.LLM_SERVICE_ERROR, "计划增强必须是 JSON 对象"),
    RESEARCH_PLAN_ENRICH_EMPTY(ErrorCode.LLM_SERVICE_ERROR, "模型未返回可应用的计划增强字段"),
    RESEARCH_PLAN_SUBJECT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究命题和研究对象不能为空"),
    RESEARCH_PLAN_ACTION_BUDGET_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "研究动作预算不合法"),
    RESEARCH_PLAN_FIELD_NOT_STRING(ErrorCode.LLM_SERVICE_ERROR, "%s 必须是字符串"),
    RESEARCH_TASK_START_FAILED(ErrorCode.BUSINESS_CONFLICT, "研究任务无法开始：%s"),
    RESEARCH_TASK_COMPLETE_FAILED(ErrorCode.BUSINESS_CONFLICT, "研究任务无法完成：%s"),
    RESEARCH_PATCH_ONLY_PENDING(ErrorCode.BUSINESS_CONFLICT, "只允许增加或替换未完成的局部研究任务"),
    RESEARCH_PATCH_KEY_PREFIX(ErrorCode.REQUEST_PARAMETER_INVALID, "局部任务编码必须使用 adaptive_ 前缀"),
    RESEARCH_PATCH_TOOL_NEWS_ONLY(ErrorCode.REQUEST_PARAMETER_INVALID, "局部重规划只能使用公开新闻搜索工具"),
    RESEARCH_PATCH_INTENT_NOT_ALLOWED(ErrorCode.REQUEST_PARAMETER_INVALID, "局部重规划意图不在白名单中"),
    RESEARCH_PATCH_FIELD_UNSAFE(ErrorCode.REQUEST_PARAMETER_INVALID, "局部重规划任务字段未通过安全校验"),
    RESEARCH_PATCH_TASK_LOCKED(ErrorCode.BUSINESS_CONFLICT, "局部任务已经执行或正在执行，不能被重写：%s"),
    RESEARCH_MISSION_FINALIZE_FAILED(ErrorCode.BUSINESS_CONFLICT, "研究任务图无法进入终态：%s"),
    RESEARCH_MISSION_TASK_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "研究任务不存在：%s"),
    RESEARCH_GAP_INPUT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究运行和证据评估不能为空"),
    RESEARCH_SOURCE_TASK_INVALID(ErrorCode.BUSINESS_CONFLICT, "只有已校验的公开新闻搜索任务可以生成临时来源"),
    RESEARCH_SOURCE_QUERY_UNSAFE(ErrorCode.REQUEST_PARAMETER_INVALID, "研究搜索词未通过安全校验"),
    RESEARCH_MISSION_STAGE_DUPLICATE(ErrorCode.DATA_INTEGRITY_ERROR, "研究任务图包含重复系统阶段：%s"),
    RESEARCH_MISSION_STAGE_MISSING(ErrorCode.DATA_INTEGRITY_ERROR, "研究任务图缺少系统阶段：%s"),
    RESEARCH_QUERY_ROUND_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "研究查询轮次必须介于 1 到 3 之间"),
    EVIDENCE_SUFFICIENCY_COUNT_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "证据充分性计数不合法"),
    RESEARCH_THESIS_REQUIRED_FOR_REPORT(ErrorCode.REQUEST_PARAMETER_INVALID, "生成命题报告需要提供研究命题"),
    EVIDENCE_CHUNK_PARAM_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "证据分块参数无效"),
    BENCHMARK_INPUT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "Benchmark 输入不能为空"),
    AGENT_CANDIDATE_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "Agent 候选不存在"),
    AGENT_CANDIDATE_UPDATED(ErrorCode.DATA_VERSION_CONFLICT, "Agent 候选已被更新"),
    AGENT_INTERPRETATION_FIELD_COUNT_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "Agent 解读字段数量不合规：%s"),
    AGENT_INTERPRETATION_FIELD_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "Agent 解读字段不符合协议"),
    AGENT_INTERPRETATION_FIELD_INVALID_DETAILED(ErrorCode.REQUEST_PARAMETER_INVALID, "Agent 解读字段不符合协议：%s"),
    AGENT_INTERPRETATION_NOT_JSON(ErrorCode.REQUEST_PARAMETER_INVALID, "Agent 解读不是合法 JSON"),
    AGENT_INTERPRETATION_REQUIRES_SUCCESS_EXPERIMENT(ErrorCode.BUSINESS_CONFLICT, "只有成功实验才能请求 Agent 解读"),
    AGENT_INTERPRETATION_TEXT_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "Agent 解读必须是非空短文本：%s"),
    ARCHIVED_EVENT_ACTION_FORBIDDEN(ErrorCode.BUSINESS_CONFLICT, "已归档事件不能执行治理操作：%s"),
    ARTICLE_LINK_UPDATED(ErrorCode.DATA_VERSION_CONFLICT, "文章关联已被更新，请刷新后重试：%s"),
    ARTICLE_MOVE_TO_SOURCE_EVENT(ErrorCode.BUSINESS_CONFLICT, "文章不能移动到原事件"),
    ARTICLE_MUST_BE_SAVED(ErrorCode.REQUEST_PARAMETER_INVALID, "文章必须先保存，才能关联事件"),
    ASYNC_TASK_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "异步任务不存在：%s"),
    ATTRIBUTION_PLAN_BUDGET_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "归因研究计划缺少反证轨道或超出总预算"),
    ATTRIBUTION_PLAN_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "归因研究计划不能为空"),
    ATTRIBUTION_REPORT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "归因报告不存在：%s"),
    ATTRIBUTION_RUN_IN_PROGRESS(ErrorCode.BUSINESS_CONFLICT, "归因研究仍在运行，暂不能删除"),
    ATTRIBUTION_RUN_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "归因研究运行不存在：%s"),
    ATTRIBUTION_TASK_SUBMIT_FAILED(ErrorCode.INTERNAL_ERROR, "归因任务提交失败，请稍后重试"),
    ATTRIBUTION_TRACK_CONTRACT_MISSING(ErrorCode.REQUEST_PARAMETER_INVALID, "归因研究轨道缺少执行合同"),
    ATTRIBUTION_TRACK_QUERY_BUDGET_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "归因研究轨道查询预算不合法"),
    AUTO_REPORT_A_SHARE_ONLY(ErrorCode.REQUEST_PARAMETER_INVALID, "自动研报仅支持六位 A 股代码"),
    AUTO_SYNC_NO_HISTORY_BACKFILL(ErrorCode.REQUEST_PARAMETER_INVALID, "自动同步禁止使用当前成分回填历史"),
    BACKTEST_DATE_OUT_OF_RANGE(ErrorCode.BUSINESS_CONFLICT, "策略回测日期已超出当前数据集范围"),
    BACKTEST_ENGINE_UNSUPPORTED_CANDIDATE(ErrorCode.BUSINESS_CONFLICT, "当前回测引擎暂不支持该策略候选"),
    BUILDING_DATASET_FROZEN_IMMUTABLE(ErrorCode.BUSINESS_CONFLICT, "只能更新尚未冻结的 BUILDING 数据集"),
    CANDIDATE_STATE_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的候选状态"),
    CANDIDATE_STATE_UNSUPPORTED_DETAILED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的候选状态：%s"),
    CAPITAL_EVAL_PERSIST_FAILED(ErrorCode.DATABASE_ERROR, "无法持久化资金行为评估"),
    CAPITAL_EVAL_READ_FAILED(ErrorCode.DATABASE_ERROR, "无法读取资金行为评估，快照=%s"),
    CAPITAL_FREEZE_DATASET_STATE_INVALID(ErrorCode.BUSINESS_CONFLICT, "当前数据集状态不允许冻结资金行为"),
    CAPITAL_FREEZE_REQUIRES_PRO_DATASET_V2(ErrorCode.BUSINESS_CONFLICT, "仅专业研究数据集 v2 支持资金行为冻结"),
    CAPITAL_INTERPRETATION_PERSIST_FAILED(ErrorCode.DATABASE_ERROR, "无法持久化资金行为解读"),
    CAPITAL_INTERPRETATION_READ_FAILED(ErrorCode.DATABASE_ERROR, "无法读取资金行为解读，id=%s"),
    CAPITAL_INTERPRETATION_UPDATE_FAILED(ErrorCode.DATABASE_ERROR, "无法更新资金行为解读，id=%s"),
    CAPITAL_SIGNAL_NOT_IN_SNAPSHOT(ErrorCode.BUSINESS_CONFLICT, "所选信号不属于当前资金行为快照"),
    CAPITAL_SNAPSHOT_INSTRUMENT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "资金行为快照对应标的不存在：%s"),
    CAPITAL_SNAPSHOT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "资金行为快照不存在：%s"),
    CAPITAL_SNAPSHOT_PERSIST_FAILED(ErrorCode.DATABASE_ERROR, "无法持久化资金行为快照"),
    CAPITAL_SNAPSHOT_READ_FAILED(ErrorCode.DATABASE_ERROR, "无法读取资金行为快照，id=%s"),
    CAPITAL_SNAPSHOT_UPDATE_FAILED(ErrorCode.DATABASE_ERROR, "无法更新资金行为快照告警，id=%s"),
    CLASSIFICATION_CHANGED(ErrorCode.DATA_VERSION_CONFLICT, "分类结果已变化，请刷新后重试"),
    CLASSIFICATION_REVIEW_READ_FAILED(ErrorCode.DATA_INTEGRITY_ERROR, "分类复核结果读取失败"),
    COMPANY_QUERY_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "请输入公司名称或股票代码"),
    CONTENT_IDEA_STATE_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的内容选题状态：%s"),
    CONTENT_UNREADABLE(ErrorCode.REQUEST_PARAMETER_INVALID, "未读取到可用内容：%s"),
    DAILY_BARS_DUPLICATE(ErrorCode.BUSINESS_CONFLICT, "日行情包含已存在的记录"),
    DAILY_BARS_IMPORT_LIMIT(ErrorCode.REQUEST_PARAMETER_INVALID, "单次最多导入 100000 条日行情"),
    DAILY_BARS_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "日行情不能为空"),
    DATASET_CHANGED_AFTER_DRAFT(ErrorCode.DATA_VERSION_CONFLICT, "数据集在草案生成后已变化，请重新生成策略草案"),
    DATASET_FACTOR_COVERAGE_MISSING(ErrorCode.BUSINESS_CONFLICT, "当前数据集不具备该因子的有效覆盖"),
    DATASET_FACTOR_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "数据集和因子不能为空"),
    DATASET_FINGERPRINT_CHANGED(ErrorCode.DATA_VERSION_CONFLICT, "数据集指纹已变化，请重新创建研究计划"),
    DATASET_FINGERPRINT_MISSING(ErrorCode.BUSINESS_CONFLICT, "数据集缺少可复现指纹"),
    DATASET_NAME_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "数据集名称不能为空"),
    DATASET_QUALITY_GATE_FAILED(ErrorCode.BUSINESS_CONFLICT, "数据集已不再满足质量门禁"),
    DATASET_QUALITY_GATE_PENDING(ErrorCode.BUSINESS_CONFLICT, "数据集尚未通过质量门禁"),
    DATASET_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "数据集不能为空"),
    DATASET_STRATEGY_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "数据集和策略描述不能为空"),
    DATASET_SYNC_RUN_IN_PROGRESS(ErrorCode.BUSINESS_CONFLICT, "该数据集已有同步任务在运行"),
    DATASET_UPDATED(ErrorCode.DATA_VERSION_CONFLICT, "数据集已被更新，请刷新后重试"),
    DATA_KIND_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "数据性质不受支持"),
    DATE_RANGE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "开始日期不能晚于结束日期"),
    EVENT_DATE_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "事件日期不能为空"),
    EVENT_MERGE_IDS_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "源事件 ID 和目标事件 ID 不能为空"),
    EVENT_MERGE_TARGET_OR_NEW_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "目标事件 ID 与新建事件选项必须且只能提供一个"),
    EVENT_MERGE_TO_SELF(ErrorCode.BUSINESS_CONFLICT, "事件不能合并到自身"),
    EVENT_STATE_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的事件状态：%s"),
    EVIDENCE_CANDIDATE_INCOMPLETE(ErrorCode.BUSINESS_CONFLICT, "候选证据结构不完整，请先补齐再沉淀"),
    EXPECTED_REVISION_MISSING(ErrorCode.REQUEST_PARAMETER_MISSING, "缺少 expectedRevision"),
    EXPERIMENT_AGENT_NOT_CONFIGURED(ErrorCode.REQUEST_PARAMETER_INVALID, "实验解读 Agent 尚未配置"),
    EXPERIMENT_AGENT_OUTPUT_INVALID(ErrorCode.EXTERNAL_SERVICE_UNAVAILABLE, "实验解读 Agent 返回内容无法通过校验"),
    EXPERIMENT_QUEUE_FULL(ErrorCode.BUSINESS_CONFLICT, "实验队列已满，请稍后重试"),
    FACTOR_DIAGNOSIS_REQUIRES_QUALITY_GATE(ErrorCode.BUSINESS_CONFLICT, "只有通过质量门禁的数据集才能运行因子诊断"),
    FACTOR_IDENTITY_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "因子命名空间、编码和版本不能为空"),
    FILE_PATH_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "文件路径不合法"),
    FINANCIALS_PROVIDER_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "该公司目录暂未接入结构化财报抓取：%s"),
    FINANCIAL_INTERPRETATION_PERSIST_FAILED(ErrorCode.DATABASE_ERROR, "无法持久化财报解读"),
    FINANCIAL_INTERPRETATION_READ_FAILED(ErrorCode.DATABASE_ERROR, "无法读取财报解读"),
    FINANCIAL_INTERPRETATION_UPDATE_FAILED(ErrorCode.DATABASE_ERROR, "无法更新财报解读，id=%s"),
    FINANCIAL_SNAPSHOT_DUPLICATE(ErrorCode.BUSINESS_CONFLICT, "财务快照包含已存在的记录"),
    FORMAL_KNOWLEDGE_REVIEW_REQUIRED(ErrorCode.BUSINESS_CONFLICT, "正式认识请在认识档案中复核或失效"),
    FREEZE_CONTEXT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "冻结请求缺少数据集、日期范围或信息截止时间"),
    FREEZE_DATE_RANGE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "冻结开始日期不能晚于结束日期"),
    FREEZE_FIELDS_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "冻结请求必须提供 from、to 和 asOfTime"),
    FREEZE_REQUEST_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "冻结请求不能为空"),
    FUNDAMENTAL_SNAPSHOT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "基本面快照不能为空"),
    FUND_ROLE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "基金角色只能是核心、卫星、防守或观察"),
    INFO_CUTOFF_AFTER_RANGE_END(ErrorCode.REQUEST_PARAMETER_INVALID, "信息截止时间不能早于研究区间结束日"),
    INSTRUMENT_ALREADY_IN_PORTFOLIO(ErrorCode.BUSINESS_CONFLICT, "该标的已在策略组合中"),
    INSTRUMENT_ALREADY_IN_WATCHLIST(ErrorCode.REQUEST_PARAMETER_INVALID, "该标的已在自选列表中"),
    INSTRUMENT_CODE_6_DIGITS(ErrorCode.REQUEST_PARAMETER_INVALID, "标的代码必须是 6 位数字"),
    INSTRUMENT_CODE_FORMAT_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "标的代码格式不正确，示例：%s"),
    INSTRUMENT_CODE_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "标的代码不能为空"),
    INVESTMENT_KNOWLEDGE_READ_FAILED(ErrorCode.DATA_INTEGRITY_ERROR, "无法读取投资认识数据"),
    INVESTMENT_KNOWLEDGE_SERIALIZE_FAILED(ErrorCode.DATA_INTEGRITY_ERROR, "无法序列化投资认识数据"),
    KNOWLEDGE_CONCLUSION_CHANGED(ErrorCode.DATA_VERSION_CONFLICT, "认识结论已变化"),
    KNOWLEDGE_DRAFT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "知识草稿不存在"),
    KNOWLEDGE_ONLY_AGENT_CANDIDATE(ErrorCode.BUSINESS_CONFLICT, "只有 Agent 候选可以沉淀为正式认识"),
    KNOWLEDGE_OUTCOME_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "知识成果不存在"),
    KNOWLEDGE_PROFILE_STATE_CHANGED(ErrorCode.DATA_VERSION_CONFLICT, "认识档案状态已变化"),
    KRX_SYMBOL_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "KRX 股票代码格式不正确"),
    LEARNING_DATASET_CREATE_CONFLICT(ErrorCode.BUSINESS_CONFLICT, "学习数据集创建期间发生并发更新"),
    LEARNING_TASK_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "学习任务不存在"),
    LIMIT_OUT_OF_RANGE(ErrorCode.REQUEST_PARAMETER_INVALID, "limit 必须在 1 到 %s 之间"),
    MAJOR_EVENT_ALREADY_RECORDED(ErrorCode.DUPLICATE_OPERATION, "该事件已记入大事记"),
    MAJOR_EVENT_SOURCE_TYPE_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的大事来源类型"),
    MARKET_DATA_RESPONSE_INVALID(ErrorCode.EXTERNAL_RESPONSE_INVALID, "行情数据返回异常"),
    MARKET_DATA_RUN_ID_MISSING(ErrorCode.DATA_INTEGRITY_ERROR, "市场数据刷新任务主键未生成"),
    MARKET_DATA_UNAVAILABLE_AGAIN(ErrorCode.MARKET_DATA_UNAVAILABLE, "行情数据暂不可用，请稍后重试"),
    MARKET_INTEL_STOCK_ONLY(ErrorCode.REQUEST_PARAMETER_INVALID, "市场情报当前仅支持股票标的"),
    MIN_CONFIDENCE_OUT_OF_RANGE(ErrorCode.REQUEST_PARAMETER_INVALID, "最低置信度必须在 0 到 100 之间"),
    NEWS_CATEGORY_UNKNOWN(ErrorCode.REQUEST_PARAMETER_INVALID, "未知或已停用的资讯分类：%s"),
    NEWS_TITLE_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "资讯标题不能为空"),
    PAGE_PARAMETER_OUT_OF_RANGE(ErrorCode.REQUEST_PARAMETER_INVALID, "页码不能小于 0，且每页数量必须在 1 到 100 之间"),
    PDF_ARCHIVED_TO_ANOTHER_COMPANY(ErrorCode.REQUEST_PARAMETER_INVALID, "该 PDF 已归档到另一家公司，请核对所选股票"),
    PDF_CORRUPT(ErrorCode.REQUEST_PARAMETER_INVALID, "PDF 文件已损坏或无法解析，请重新下载后上传"),
    PDF_SIZE_LIMIT(ErrorCode.REQUEST_PARAMETER_INVALID, "PDF 文件大小必须在 30MB 以内"),
    PIT_POOL_NO_VALID_MEMBERS(ErrorCode.REQUEST_PARAMETER_INVALID, "point-in-time 股票池没有有效成分"),
    PIT_POOL_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "请先导入 point-in-time 股票池"),
    PORTFOLIO_ENTRY_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "组合条目不存在"),
    PORTFOLIO_SUPPORTS_FUND_STOCK_ONLY(ErrorCode.REQUEST_PARAMETER_INVALID, "策略组合只支持基金和股票"),
    PUBLIC_REPORT_IDENTITY_INCOMPLETE(ErrorCode.REQUEST_PARAMETER_INVALID, "公开研报身份不完整"),
    QUANT_DATASET_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "量化数据集不存在"),
    QUANT_EXPERIMENT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "量化实验不存在"),
    QUANT_SYNC_RUN_ID_MISSING(ErrorCode.DATA_INTEGRITY_ERROR, "量化数据同步任务主键未生成"),
    RADAR_EVENT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "雷达事件不存在"),
    RADAR_INTERPRETATION_READ_FAILED(ErrorCode.DATABASE_ERROR, "无法读取雷达事件解读"),
    RADAR_INTERPRETATION_UNAVAILABLE(ErrorCode.LLM_SERVICE_ERROR, "雷达事件解读暂不可用"),
    RADAR_INTERPRETATION_UPDATE_FAILED(ErrorCode.DATABASE_ERROR, "无法更新雷达事件解读，id=%s"),
    READY_DATASET_IMMUTABLE(ErrorCode.BUSINESS_CONFLICT, "已就绪数据集不可原地修改，请创建新版本"),
    RECORD_UPDATED(ErrorCode.DATA_VERSION_CONFLICT, "记录已更新，请刷新后重试"),
    RECORD_UPDATED_AGAIN(ErrorCode.DATA_VERSION_CONFLICT, "记录已被更新，请刷新后再试"),
    REPORT_ARCHIVED_TO_ANOTHER_COMPANY(ErrorCode.REQUEST_PARAMETER_INVALID, "该公开研报已归档到另一家公司"),
    REPORT_COMPANY_MISMATCH(ErrorCode.REQUEST_PARAMETER_INVALID, "公开研报与所选公司不匹配"),
    REPORT_DIRECTORY_UNAVAILABLE(ErrorCode.EXTERNAL_SERVICE_UNAVAILABLE, "公开研报目录暂时不可用"),
    REPORT_DOWNLOAD_FAILED(ErrorCode.EXTERNAL_SERVICE_UNAVAILABLE, "公开研报原文下载失败"),
    REPORT_FILE_PATH_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "研报文件路径不合法：%s"),
    REPORT_FINANCIALS_COMPANY_MISMATCH(ErrorCode.REQUEST_PARAMETER_INVALID, "研报与财报不属于同一家公司"),
    REPORT_PDF_SIZE_LIMIT(ErrorCode.REQUEST_PARAMETER_INVALID, "研报 PDF 大小必须在 30MB 以内"),
    REPORT_SAVE_FAILED(ErrorCode.FILE_OPERATION_ERROR, "公开研报原文保存失败"),
    REPORT_SOURCE_MISMATCH(ErrorCode.REQUEST_PARAMETER_INVALID, "研报来源不匹配"),
    REPORT_SOURCE_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的公开研报来源：%s"),
    REPORT_STORAGE_PATH_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "研报存储路径不合法"),
    REPORT_URL_NOT_ALLOWED(ErrorCode.REQUEST_PARAMETER_INVALID, "公开研报原文地址不在允许范围内"),
    REQUEST_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "请求不能为空"),
    REQUIRED_FIELD_EMPTY(ErrorCode.REQUEST_PARAMETER_INVALID, "必填字段不能为空：%s"),
    REQUIRED_FIELD_MISSING(ErrorCode.REQUEST_PARAMETER_INVALID, "缺少必填字段：%s"),
    RESEARCH_AGENT_CANNOT_RUN(ErrorCode.BUSINESS_CONFLICT, "研究 Agent 无法进入运行状态"),
    RESEARCH_AGENT_READ_FAILED(ErrorCode.DATA_INTEGRITY_ERROR, "无法读取研究 Agent 数据"),
    RESEARCH_AGENT_REQUEST_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究 Agent 请求不能为空"),
    RESEARCH_AGENT_RUN_FAILED(ErrorCode.INTERNAL_ERROR, "研究 Agent 运行失败"),
    RESEARCH_AGENT_RUN_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "研究 Agent 运行不存在"),
    RESEARCH_AGENT_SERIALIZE_FAILED(ErrorCode.DATA_INTEGRITY_ERROR, "无法序列化研究 Agent 数据"),
    RESEARCH_DRAFT_EVIDENCE_INVALID(ErrorCode.DATA_INTEGRITY_ERROR, "已存储的研究草稿证据不合法"),
    RESEARCH_DRAFT_EVIDENCE_NOT_SERIALIZABLE(ErrorCode.DATA_INTEGRITY_ERROR, "研究草稿证据无法序列化"),
    RESEARCH_DRAFT_FACTOR_DEFINITION_CHANGED(ErrorCode.DATA_VERSION_CONFLICT, "研究草稿的因子定义已变化，请重新创建研究计划"),
    RESEARCH_DRAFT_FACTOR_MISMATCH(ErrorCode.BUSINESS_CONFLICT, "研究草稿与本次因子身份不一致"),
    RESEARCH_DRAFT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "研究草稿不存在：%s"),
    RESEARCH_DRAFT_REQUEST_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究草稿请求不能为空"),
    RESEARCH_FACTOR_VERSION_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "研究因子版本不存在：%s"),
    RESEARCH_FINDING_STANCE_SUMMARY_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究发现的立场和摘要不能为空"),
    RESEARCH_PLAN_REQUIRES_FROZEN_DATASET(ErrorCode.BUSINESS_CONFLICT, "只有已冻结且具备指纹的数据集才能生成研究计划"),
    RESEARCH_PLAN_STATE_CHANGED(ErrorCode.BUSINESS_CONFLICT, "研究计划已批准、已运行或状态已变化"),
    RESEARCH_QUESTION_SUBJECT_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "研究问题、主体类型和主体名称不能为空"),
    RESEARCH_QUESTION_TOO_LONG(ErrorCode.REQUEST_PARAMETER_INVALID, "研究问题不能超过500字"),
    RESEARCH_RUN_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "研究运行不存在"),
    RESEARCH_STAGE_SKIP_NOT_ALLOWED(ErrorCode.REQUEST_PARAMETER_INVALID, "不能跳过研究阶段"),
    RESEARCH_SUBJECT_TYPE_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "不支持的研究主体类型：%s"),
    RESEARCH_TOPIC_AT_LEAST_ONE(ErrorCode.REQUEST_PARAMETER_INVALID, "至少需要提供一个研究主题编码"),
    REVIEW_FIELDS_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "复盘日期、事实、推理和行动不能为空"),
    REVIEW_RECORD_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "复习记录不存在"),
    REVIEW_RECORD_UPDATED(ErrorCode.DATA_VERSION_CONFLICT, "复习记录已更新，请刷新后重试"),
    SEARCH_LIMIT_OUT_OF_RANGE(ErrorCode.REQUEST_PARAMETER_INVALID, "搜索结果数量必须在 1–20 之间"),
    SECTOR_CATEGORY_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "板块分类不能为空"),
    SECTOR_CATEGORY_UNSUPPORTED(ErrorCode.REQUEST_PARAMETER_INVALID, "板块分类必须是 %s"),
    SECTOR_SEARCH_TERM_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "板块搜索词不能为空"),
    SECTOR_USE_WATCHLIST_API(ErrorCode.REQUEST_PARAMETER_INVALID, "板块请使用板块关注接口"),
    SEC_CIK_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "SEC CIK 格式不正确"),
    SOURCE_ID_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "信息源 ID 不能为空"),
    SOURCE_TYPE_REFERENCE_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "来源类型和来源标识不能为空"),
    SQLITE_GENERATED_KEY_MISSING(ErrorCode.DATA_INTEGRITY_ERROR, "SQLite 未返回生成的主键"),
    STATUS_MISSING(ErrorCode.REQUEST_PARAMETER_MISSING, "缺少 status"),
    STOCK_CODE_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "股票代码不能为空"),
    STOCK_POOL_DUPLICATE(ErrorCode.BUSINESS_CONFLICT, "股票池包含已存在的记录"),
    STOCK_POOL_MEMBER_INCOMPLETE(ErrorCode.REQUEST_PARAMETER_INVALID, "股票池成员缺少日期或标的代码"),
    STOCK_POOL_MEMBER_LIMIT(ErrorCode.REQUEST_PARAMETER_INVALID, "股票池成员不能为空且单次不能超过 100000 条"),
    STOCK_POOL_SOURCE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "股票池来源只能是 POINT_IN_TIME 或 CURRENT_SNAPSHOT"),
    STOCK_RESEARCH_CARD_EXISTS(ErrorCode.BUSINESS_CONFLICT, "该股票已存在研究卡"),
    STOCK_RESEARCH_CARD_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "股票研究卡不存在"),
    STOCK_RESEARCH_STAGE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "股票研究阶段不合法"),
    STOCK_ROLE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "股票角色只能是观察、模拟或真实验证"),
    STRATEGY_CANDIDATE_ARCHIVED(ErrorCode.BUSINESS_CONFLICT, "策略候选已归档，请重新同步目录"),
    STRATEGY_CANDIDATE_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "策略候选不存在"),
    STRATEGY_CODE_EXISTS(ErrorCode.DUPLICATE_OPERATION, "策略编码已存在"),
    STRATEGY_COVERAGE_STALE(ErrorCode.BUSINESS_CONFLICT, "数据变化后策略因子覆盖率已不足，请重新生成草案"),
    STRATEGY_DATE_LOCK_FAILED(ErrorCode.INTERNAL_ERROR, "策略日期锁定失败"),
    STRATEGY_DRAFT_MUST_PASS_VALIDATION(ErrorCode.BUSINESS_CONFLICT, "只有通过校验的策略草案才能确认"),
    STRATEGY_DRAFT_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "策略草案不存在"),
    STRATEGY_MATERIAL_LIBRARY_NOT_SYNCED(ErrorCode.RESOURCE_NOT_FOUND, "策略素材库尚未同步"),
    STRATEGY_STATE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "策略状态不合法"),
    STRATEGY_TEMPLATE_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "策略模板不存在"),
    STRATEGY_VERSION_CREATE_FAILED(ErrorCode.INTERNAL_ERROR, "策略版本创建失败"),
    STRATEGY_VERSION_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "策略版本不存在"),
    STRATEGY_VERSION_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "策略版本不能为空"),
    SYNC_REQUIRES_REAL_DATASET(ErrorCode.REQUEST_PARAMETER_INVALID, "只能为真实研究数据集同步市场数据"),
    TASK_FINAL_ANSWER_EXISTS(ErrorCode.BUSINESS_CONFLICT, "该任务已存在最终答案"),
    TEMP_SOURCE_NAME_URL_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "临时信息源名称和 URL 不能为空"),
    THESIS_CRITERIA_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "投资逻辑、买入条件、失效条件和观察重点不能为空"),
    TOPIC_NAME_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "主题名称不能为空"),
    TOPIC_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "主题不存在"),
    UNKNOWN_COMPATIBILITY_STATE(ErrorCode.REQUEST_PARAMETER_INVALID, "未知的兼容状态"),
    UNKNOWN_FACTOR(ErrorCode.REQUEST_PARAMETER_INVALID, "未知因子：%s"),
    UNKNOWN_TOPIC_CODE(ErrorCode.REQUEST_PARAMETER_INVALID, "未知研究主题编码：%s"),
    UPLOAD_NOT_PDF(ErrorCode.REQUEST_PARAMETER_INVALID, "上传文件不是有效 PDF"),
    WATCHED_SECTOR_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "关注板块不存在"),
    WATCHLIST_ITEM_ID_REQUIRED(ErrorCode.REQUEST_PARAMETER_INVALID, "自选条目 id 不能为空"),
    WATCHLIST_ITEM_NOT_FOUND(ErrorCode.RESOURCE_NOT_FOUND, "自选条目不存在"),
    WATCHLIST_ITEM_NOT_STOCK_OR_FUND(ErrorCode.REQUEST_PARAMETER_INVALID, "该条目不是普通股票或基金自选"),
    WATCHLIST_RELATION_STATE_CONFLICT(ErrorCode.BUSINESS_CONFLICT, "关注关系状态冲突"),
    WATCHLIST_TYPE_INVALID(ErrorCode.REQUEST_PARAMETER_INVALID, "普通自选类型只能是股票或基金"),
    WEIGHT_OUT_OF_RANGE(ErrorCode.REQUEST_PARAMETER_INVALID, "权重必须在 0 到 100 之间"),
    WEIGHT_TOTAL_EXCEEDS_100(ErrorCode.REQUEST_PARAMETER_INVALID, "目标权重合计不能超过 100%"),;

    private final ErrorCode errorCode;
    private final String message;

    BizErrorCode(ErrorCode errorCode, String message) {
        this.errorCode = errorCode;
        this.message = message;
    }

    /**
     * 关联的通用错误码，提供对外错误码与 HTTP 状态。
     *
     * @return 关联的 {@link ErrorCode}。
     */
    public ErrorCode getErrorCode() {
        return errorCode;
    }

    /**
     * 业务报错信息。
     *
     * @return 具体的可读报错信息。
     */
    public String getMessage() {
        return message;
    }

    /**
     * 使用参数渲染报错信息中的占位符。
     *
     * @param args 占位符实参。
     * @return 渲染后的报错信息。
     */
    public String format(Object... args) {
        return String.format(message, args);
    }
}